/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur_Billets;

import requete.ConsoleServeur;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.Properties;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.table.DefaultTableModel;
import PackageSecurite.Securite;

/**
 *
 * @author Benjamin
 */
public class Serveur_Billets extends javax.swing.JFrame  implements ConsoleServeur{

    /**
     * Creates new form Serveur_Billets
     */
    private int port;
    public static SecretKey serveurSymmetric;
    public static SecretKey hmacSymmetric;
    
    public Serveur_Billets() throws NoSuchAlgorithmException {
        initComponents();
        TraceEvenements("serveur#initialisation#main");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_co = new javax.swing.JButton();
        text_co = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableauEvenements = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_co.setText("Se connecter");
        button_co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_coActionPerformed(evt);
            }
        });

        text_co.setText("Serveur inactif");

        TableauEvenements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORIGINE", "REQUETE", "THREAD"
            }
        ));
        jScrollPane2.setViewportView(TableauEvenements);

        jLabel1.setText("Serveur billets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(button_co)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text_co, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_co)
                    .addComponent(button_co))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_coActionPerformed
        
        text_co.setText("Serveur actif");
        Properties prop = new Properties();
        FileInputStream in = null;
        try {
            in = new FileInputStream("prop.properties");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Serveur_Billets.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            prop.load(in);
        } catch (IOException ex) {
            Logger.getLogger(Serveur_Billets.class.getName()).log(Level.SEVERE, null, ex);
        }
        button_co.setEnabled(false);
        port = Integer.parseInt(prop.getProperty("PORT_BILLETS"));
        System.out.println("port : " + port);
        TraceEvenements("serveur#acquisition du port#main");
        
        Thread_serveur ts;
        try {
            ts = new Thread_serveur(port, new ListeTaches(), this, new Zone_queue_socket());
            ts.start();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Serveur_Billets.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_button_coActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serveur_Billets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Serveur_Billets().setVisible(true);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(Serveur_Billets.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void TraceEvenements(String commentaire)
    {
        Vector ligne = new Vector();
        StringTokenizer parser = new StringTokenizer(commentaire,"#");
        while (parser.hasMoreTokens())
        ligne.add(parser.nextToken());
        DefaultTableModel dtm = (DefaultTableModel)TableauEvenements.getModel();
        dtm.insertRow(dtm.getRowCount(),ligne);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableauEvenements;
    private javax.swing.JButton button_co;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel text_co;
    // End of variables declaration//GEN-END:variables
}
